### ISSUE TITLE
bias似乎重复扣除了两次

### ISSUE THREAD

**Issue by You-zeyi** [cnqiangfu/PL-VINS#1]
在send_imu里面processIMU之前扣除了一次bias（vins-mono源代码中没有），而processIMU里做预计分又扣除了一次。

**Comment by cnqiangfu** [comment]
> 在send_imu里面processIMU之前扣除了一次bias（vins-mono源代码中没有），而processIMU里做预计分又扣除了一次。

初始版本代码还没被优化，你可以看到send_IMU中的bias是０

**Comment by You-zeyi** [comment]
> > 在send_imu里面processIMU之前扣除了一次bias（vins-mono源代码中没有），而processIMU里做预计分又扣除了一次。
> 
> 初始版本代码还没被优化，你可以看到send_IMU中的bias是０

非常棒的工作，特别对LSD的改进，很有意义
