### ISSUE TITLE
image_node_b与plvins_estimator节点挂掉

### ISSUE THREAD

**Issue by ThornsOoO** [cnqiangfu/PL-VINS#18]
在开始play bag文件时报错
[image_node_b-7] process has died [pid 13501, exit code -11, cmd /home/cyk/catkin_plvins/devel/lib/image_node_b/image_node_b __name:=image_node_b __log:=/home/cyk/.ros/log/8153462e-06f4-11ec-bd0b-70b5e8388aac/image_node_b-7.log].
log file: /home/cyk/.ros/log/8153462e-06f4-11ec-bd0b-70b5e8388aac/image_node_b-7*.log
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0827 13:06:48.249131 13508 solver.cc:507] Terminating: Invalid configuration. Solver::Options::num_linear_solver_threads = -1. Violated constraint: Solver::Options::num_linear_solver_threads > 0
[plvins_estimator-5] process has died [pid 13499, exit code -11, cmd /home/cyk/catkin_plvins/devel/lib/plvins_estimator/plvins_estimator __name:=plvins_estimator __log:=/home/cyk/.ros/log/8153462e-06f4-11ec-bd0b-70b5e8388aac/plvins_estimator-5.log].
log file: /home/cyk/.ros/log/8153462e-06f4-11ec-bd0b-70b5e8388aac/plvins_estimator-5*.log

**Comment by Grandzxw** [comment]
请问您怎么解决image_node_b-7问题呢？谢谢

**Comment by ThornsOoO** [comment]
不好意思，具体忘记了&nbsp; 但是全都是在Issues里找到的解决办法




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnqiangfu/PL-VINS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 下午3:27
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [cnqiangfu/PL-VINS] image_node_b与plvins_estimator节点挂掉 (#18)





 
请问您怎么解决image_node_b-7问题呢？谢谢
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
