### ISSUE TITLE
[image_node_b-7] process has died!!!

### ISSUE THREAD

**Issue by ccq0905** [cnqiangfu/PL-VINS#24]
播放Euroc包时提示
[image_node_b-7] process has died [pid 10194, exit code -11, cmd /home/ccq/PL_vins/devel/lib/image_node_b/image_node_b __name:=image_node_b __log:=/home/ccq/.ros/log/faeff3f0-f2fe-11ec-9be8-0bf2cc679f3e/image_node_b-7.log]
在image_node_b.cpp里也修改了文件绝对路径，求解决办法！
我用的Ubuntu20+OpenCV4.5.3。

**Comment by lmyhit** [comment]
你好，请问怎么解决的这个问题？我也遇到了。谢谢！

**Comment by YoungHaulk** [comment]
@cnqiangfu 您好！我也在image_node_b.cpp中将配置文件的路径修改成绝对路径了，跟踪图像仍然没有显示。请问这是怎么回事呢？电脑配置:ubuntu20.04+opencv3.3.1+eigen3.3.9
